name: Feature Request
description: File a feature request.
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        We will consider this feature request as soon as we are able and appreciate your patience.
        In the meantime, please feel free to check out our [_contributing guide_](https://github.com/samgaudet/mkdocs-madlibs/blob/main/CONTRIBUTING.md) and explore making the required changes yourself.
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see changed?
      description: Provide specific pseudo-code, renderings, or other descriptive details.
      placeholder: Tell us what you want!
      value: "A shiny new feature!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/samgaudet/mkdocs-madlibs/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
